# Vagrantfile 

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider :virtualbox do |v|
    v.memory = 4096
    v.cpus = 2
    v.linked_clone = true
  end

# Master
config.vm.define "KubeMaster" do |kubemaster|
  kubemaster.vm.hostname = "kube-master"
  kubemaster.vm.network :public_network, bridge: "Killer E2600 Gigabit Ethernet Controller", ip: "192.168.1.20"
end

# Worker 1
config.vm.define "worker01" do |worker01|
  worker01.vm.hostname = "worker01"
  worker01.vm.network :public_network, bridge: "Killer E2600 Gigabit Ethernet Controller", ip: "192.168.1.30"
end

# Worker 2
config.vm.define "worker02" do |worker02|
  worker02.vm.hostname = "worker02"
  worker02.vm.network :public_network, bridge: "Killer E2600 Gigabit Ethernet Controller", ip: "192.168.1.40"
end
end
