kind: Pod
apiVersion: v1
metadata:
  name: lab6-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: lab6-pv-claim
  containers:
    - name: pv-container
      image: httpd
      volumeMounts:
        - mountPath: "/var/www"
          name: pv-storage
